protocol = "omega-platinum"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-omega"
bugtracker = "https://github.com/yaq-project/yaqd-omega/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-omega"

[config]

[state]

[messages]

